### ISSUE TITLE
Question about Electric Vehicles

### ISSUE THREAD

**Issue by undarl** [sirenfal-factorio/Localized_Charging#1]
Sorry about abusing the issues system -- seemed like the easiest way to reach you.

I've been messing around with Localized Charging and enjoying it greatly. So far I've successfully modded down the base charging pole draw -- I am still young as a Factorio player, and my factories choke on 40MW/s power draws. :) I'm looking at adding additional charging poles, probably three more as progressions by half from the base charging value (40/20/10/5 MW/s). That much I have a handle on.

What I can't seem to wrap my brain around is how to enable a vehicle to use battery power and be wirelessly charged. The poles work great on me and on the electric locomotive, but I haven't gotten anything else to work.

I get that grids need to be added and that the vehicle name needs to be on the electric_vehicles list in control. However, my modded vehicle attempts seem to be dumped from the chargeable list by the validity check in on_event, and they never actually draw battery power to run.

Can you provide any insight?

Thanks.

**Comment by avosirenfal** [comment]
Hey, no problem. Please pastebin the prototype of the vehicle you're trying to work with.

Where exactly in control.lua do you suspect it's skipping your vehicle?

**Comment by undarl** [comment]
I'm currently trying to electrify the AAI Hauler. My entity definition for it: https://pastebin.com/8F1zZned

I've added it to the electric vehicles table in control. From the looks of the debug outputs I slapped into the on_tick function, it gets added to the global.vehicles list on creation, is recognized as having a grid on the first tick, then removed as invalid on the second.

**Comment by avosirenfal** [comment]
What exactly is happening? Charging the batteries in the grid and powering the vehicle with the batteries are two separate steps.

Do the batteries charge?

**Comment by undarl** [comment]
Sorry about that. Let me explain more fully.

The hauler batteries do not charge. 

I threw debug prints into LC's on_tick function, in both the validity check and grid check sections at the beginning. When I place an electric locomotive it shows a steady recognition of the loco's grid every tick. Battery charging happens as expected.

Upon placing a modded hauler, I get recognition of the hauler's grid on the first tick, then a failure of the validity check on the second. I'm not sure what's causing it to become invalid, but two ticks after it's placed LC no longer recognizes it. No charging takes place. Apparent invalidity aside the hauler continues to exist just fine, and will run if fueled.

**Comment by avosirenfal** [comment]
The only reason that would happen that I can think of would be if AAI or another mod is deleting or replacing the vehicle entity. An entity reference only becomes invalid if that entity has been deleted or destroyed.

You could invert the loop to check for electric vehicles around every charging tower, but my code still has to have a valid reference to the vehicle at all times to keep draining it's batteries for fuel.

Unfortunately, Factorio doesn't fire events for destroying or creating an entity in that way so there's no way on my side to detect it. If that is actually what's happening AAI would have to be modified or raise an event to fix it. Luckily, at a glance AAI *does* raise an event for what I'm guessing is happening here.

I don't have time to verify in detail that's actually what's happening, but very briefly looking the `unit_create_entity_from_entity` function in AAI looks like the suspect here.

This is the code that raises the event within that function:

```			raise_event("on_entity_replaced", 
				{	new_entity = entity, 
					new_entity_unit_number = entity.unit_number, 
					old_entity = source_entity, 
					old_entity_unit_number = source_entity.unit_number})
```

So something like this (with print debugging) might be the fix:

```
remote.add_interface("Localized_Charging", {
	on_entity_replaced = function(event)
		if(event.old_entity in global.vehicles) then
			-- replace old_entity with event.new_entity
		end
	end
})
```

**Comment by undarl** [comment]
Aha! Thanks so much for the pointer. I'm new enough that I would not have thought to follow that thread.

AAI Programmable Vehicles is indeed the author of all of my pain. Creating the remote on_entity_replaced interface allowed the batteries to charge, but there's also a bunch more energy code in there that is preventing your battery fueling code from working.

I disabled AAIPV and was immediately able to get the hauler charging and running on batteries. I also whipped up a mini-mod to add a grid to the regular car and add it to LC via another remote interface function. As a side effect of all of this I now understand what your battery power and charging code is doing and comprehend a fair amount more about how Factorio mods are put together in general.

Thanks again for your help. I'm going to dive back into AAIPV and see if I can make it behave.

**Comment by undarl** [comment]
Success! As it turns out, AAIPV uses its own system to manage vehicle energy at a higher level of abstraction. I added battery fueling functions based on yours (with attribution) to that system and everything works well. Earendel (the AAI author) has expressed interest in possibly adding the functionality into the mod.

I've currently made the following edits to Localized Charging:
* Optional dependence on AAIPV
* API function to handle AAIPV's entity switching
* API function to allow other mods to add items to the electric_vehicles list
* Addition to global.vehicles list to indicate vehicles (like AAIPV units) that should not be battery-fueled by LC, plus logic to enforce it
* Three additional charging poles (2.5/5/10 MW/s charge rates)

Once I've had a chance to clean things up a bit and test them more fully, would you be open to a pull request?

**Comment by avosirenfal** [comment]
Absolutely :)
